version: '3'

services:
    nginx:
        image: nginx:1.13-alpine
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
